pub const G_AND: &[&str] = &["and"];
pub const G_OR: &[&str] = &["or"];
pub const G_NOT: &[&str] = &["not", "neg"];
pub const G_IMPLIES: &[&str] = &["=>", "implies"];
pub const G_IF: &[&str] = &["if"];
pub const G_IFF: &[&str] = &["<=>", "iff"];
pub const G_FORALL: &[&str] = &["AA", "forall"];
pub const G_EXISTS: &[&str] = &["EE", "exists"];
pub const G_BOT: &[&str] = &["_|_", "bot"];
pub const G_TOP: &[&str] = &["TT", "top"];
pub const G_VDASH: &[&str] = &["|--", "vdash"];
pub const G_MODELS: &[&str] = &["|==", "models"];
