pub const G_AND: &'static[&str] = &["and"];
pub const G_OR: &'static[&str] = &["or"];
pub const G_NOT: &'static[&str] = &["not", "neg"];
pub const G_IMPLIES: &'static[&str] = &["=>", "implies"];
pub const G_IF: &'static[&str] = &["if"];
pub const G_IFF: &'static[&str] = &["<=>", "iff"];
pub const G_FORALL: &'static[&str] = &["AA", "forall"];
pub const G_EXISTS: &'static[&str] = &["EE", "exists"];
pub const G_BOT: &'static[&str] = &["_|_", "bot"];
pub const G_TOP: &'static[&str] = &["TT", "top"];
pub const G_VDASH: &'static[&str] = &["|--", "vdash"];
pub const G_MODELS: &'static[&str] = &["|==", "models"];