pub const G_EQ: &[&str] = &["="];
pub const G_NE: &[&str] = &["!=", "ne"];
pub const G_LT: &[&str] = &["<", "lt"];
pub const G_GT: &[&str] = &[">", "gt"];
pub const G_LE: &[&str] = &["<=", "le"];
pub const G_GE: &[&str] = &[">=", "ge"];
pub const G_PREC: &[&str] = &["-<", "prec"];
pub const G_PRECEQ: &[&str] = &["-<=", "preceq"];
pub const G_SUCC: &[&str] = &[">-", "succ"];
pub const G_SUCCEQ: &[&str] = &[">-=", "succeq"];
pub const G_IN: &[&str] = &["in"];
pub const G_NOTIN: &[&str] = &["!in", "notin"];
pub const G_SUBSET: &[&str] = &["sub", "subset"];
pub const G_SUPSET: &[&str] = &["sup", "supset"];
pub const G_SUBSETEQ: &[&str] = &["sube", "subseteq"];
pub const G_SUPSETEQ: &[&str] = &["supe", "supseteq"];
pub const G_EQUIV: &[&str] = &["-=", "equiv"];
pub const G_CONG: &[&str] = &["~=", "cong"];
pub const G_APPROX: &[&str] = &["~~", "approx"];
pub const G_PROP: &[&str] = &["prop", "propto"];
