pub const G_EQ: &'static[&str] = &["="];
pub const G_NE: &'static[&str] = &["!=", "ne"];
pub const G_LT: &'static[&str] = &["<", "lt"];
pub const G_GT: &'static[&str] = &[">", "gt"];
pub const G_LE: &'static[&str] = &["<=", "le"];
pub const G_GE: &'static[&str] = &[">=", "ge"];
pub const G_PREC: &'static[&str] = &["-<", "prec"];
pub const G_PRECEQ: &'static[&str] = &["-<=", "preceq"];
pub const G_SUCC: &'static[&str] = &[">-", "succ"];
pub const G_SUCCEQ: &'static[&str] = &[">-=", "succeq"];
pub const G_IN: &'static[&str] = &["in"];
pub const G_NOTIN: &'static[&str] = &["!in", "notin"];
pub const G_SUBSET: &'static[&str] = &["sub", "subset"];
pub const G_SUPSET: &'static[&str] = &["sup", "supset"];
pub const G_SUBSETEQ: &'static[&str] = &["sube", "subseteq"];
pub const G_SUPSETEQ: &'static[&str] = &["supe", "supseteq"];
pub const G_EQUIV: &'static[&str] = &["-=", "equiv"];
pub const G_CONG: &'static[&str] = &["~=", "cong"];
pub const G_APPROX: &'static[&str] = &["~~", "approx"];
pub const G_PROP: &'static[&str] = &["prop", "propto"];