[package]
name = "asciimath"
version = "0.1.0"
authors = ["trivernis <trivernis@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
charred = "0.3.0"
maplit = "1.0.2"
lazy_static = "1.4.0"